//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ_KD2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examenations
    {
        public int ID_Student { get; set; }
        public Nullable<int> Ref_Stud { get; set; }
        public Nullable<int> Ref_Subj { get; set; }
        public Nullable<int> Mark { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
